environment = {__NEXT_PRIVATE_PREBUNDLED_REACT = "next"}

[build]
  command = "npm run build"
  publish = ".next"

[template]
  incoming-hooks = ["WixBookings"]

[template.environment]
  NEXT_PUBLIC_WIX_CLIENT_ID = "Wix Headless Client ID"
