name: Setup Playwright
on:
  workflow_dispatch:
    inputs:
      runner-os:
        required: true
        type: string
      yarn-cache-dir:
        required: true
        type: string
      playwright-version:
        required: true
        type: string
jobs:
  install-playwright:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'
      - uses: actions/cache@v3
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ inputs.yarn-cache-dir }}
          key: ${{ inputs.runner-os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ inputs.runner-os }}-yarn-
      - name: Install dependencies
        run: yarn
      - name: Cache Playwright Browsers for Playwright's Version
        id: cache-playwright-browsers
        uses: actions/cache@v3
        with:
          path: ~/.cache/ms-playwright
          key: playwright-browsers-${{ inputs.playwright-version }}
      - name: Setup Playwright
        if: steps.cache-playwright-browsers.outputs.cache-hit != 'true'
        run: yarn playwright install --with-deps
