name: Setup Playwright
on:
  workflow_dispatch:
jobs:
  prepare-version:
    runs-on: ubuntu-latest
    outputs:
      playwright-version: $(npm ls @playwright/test | grep @playwright | sed 's/.*@//')
  install-playwright:
    runs-on: ubuntu-latest
    needs: prepare-version
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'
      - uses: c-hive/gha-yarn-cache@v2
      - name: Install dependencies
        run: yarn
      - name: Store Playwright's Version
        run: |
          PLAYWRIGHT_VERSION=${{ needs.prepare-version.outputs.playwright-version }}
          echo "Playwright's Version: $PLAYWRIGHT_VERSION"
          echo "PLAYWRIGHT_VERSION=$PLAYWRIGHT_VERSION" >> $GITHUB_ENV
      - name: Cache Playwright Browsers for Playwright's Version
        id: cache-playwright-browsers
        uses: actions/cache@v3
        with:
          path: ~/.cache/ms-playwright
          key: playwright-browsers-${{ needs.prepare-version.outputs.playwright-version }}
      - name: Setup Playwright
        if: steps.cache-playwright-browsers.outputs.cache-hit != 'true'
        run: yarn playwright install --with-deps
