name: Netlify E2E
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  netlify-e2e:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "dir=$(yarn cache dir)"
      - name: Store Playwright's Version
        id: store-playwright-version
        run: |
          PLAYWRIGHT_VERSION=$(npm ls @playwright/test | grep @playwright | sed 's/.*@//')
          echo "Playwright's Version: $PLAYWRIGHT_VERSION"
          echo "PLAYWRIGHT_VERSION=$PLAYWRIGHT_VERSION" >> $GITHUB_OUTPUT
      - uses: ./.github/actions/setup-e2e
        with:
          runner-os: ${{runner.os}}
          playwright-version: ${{ steps.store-playwright-version.outputs.PLAYWRIGHT_VERSION }}
          yarn-cache-dir: ${{ steps.yarn-cache-dir-path.outputs.dir }}
      - name: Waiting for 200 from the Netlify Preview
        uses: jakepartusch/wait-for-netlify-action@v1.4
        id: waitFor200
        with:
          site_name: "wix-appointments-subscriptions-nextjs"
          max_timeout: 360 # 6 Minutes, depends on your build pipeline duration
      - name: Run E2E Tests on Netlify URL
        run: REMOTE_PROVIDER=netlify yarn e2e
        env:
          PLAYWRIGHT_TEST_BASE_URL: ${{ steps.waitFor200.outputs.url }}
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report-netlify
          path: playwright-report/
          retention-days: 10
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: screenshots-netlify
          path: tests/e2e/__screenshots__
          retention-days: 10
