name: Vercel E2E
on:
  deployment_status:
jobs:
  vercel-e2e:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'yarn'
    - uses: ./.github/workflows/setup-e2e.yml@add-e2e
    - name: Run E2E Tests on Vercel URL
      run: REMOTE_PROVIDER=vercel yarn e2e
      env:
        PLAYWRIGHT_TEST_BASE_URL: ${{ github.event.deployment_status.target_url }}
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report-vercel
        path: playwright-report/
        retention-days: 10
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: screenshots-vercel
        path: tests/e2e/__screenshots__
        retention-days: 10
